version: "3.9"

networks:
  database_net:
    name: database_net
    driver: bridge
  broker_net:
    name: broker_net
    driver: bridge

services:
  database:
    image: postgres
    container_name: postgres-hx
    volumes:
      - ~/.docker-conf/postgres/data/:/var/lib/postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: postgres
    networks:
      - database_net
